namespace: core-dev
fullname: filter-service
name: filter-service
image:
  tag: latest # set to your local image tag if needed

# settings for ingest
keyServiceURL: "key-service-core-dev.core-dev.svc.cluster.local:8095"
serverUuid: "9d3c78ff-22f3-4441-a5d1-85c636d486ff"
service:
  type: "NodePort"
  replicaCount: 1

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-dev"
    certmanager.k8s.io/acme-dns01-provider: "dev-dns"
    kubernetes.io/ingress.allow-http: "false"
  path: /
  hosts:
    - dev.ubirch.com
  tls:
    - secretName: filter-dev-ubirch-com-certificate
      hosts:
        - filter.dev.ubirch.com

redis:
  #not using master and slave till now, should I?
  masterURL: "redis-stable-master.core-dev.svc.cluster.local:6379"
  slaveURL: "redis-stable-slave.core-dev.svc.cluster.local:6379"
  SSL: "true"
  host: ""
  # This port should be the ssl or non-ssl port depending on the value of the key "SSL"
  port: ""
  pw: "redis-secrets"
  usecluster: ""
  name: "hashes_payload"

kafka:
  consumer:
    URL: "kafka.core-dev.svc.cluster.local:9092"
    topic: "json.to.sign"
    groupID: ""
    errortopic: "com.ubirch.filter.error"
    timeout: 1
    poolrec: 500
  producer:
    URL: "kafka.core-dev.svc.cluster.local:9092"
    errortopic: "com.ubirch.filter.error"
    rejectiontopic: "com.ubirch.filter.rejection"
    topic: "com.ubirch.eventlog.encoder"
    timeout: 2

metrics:
  prometheus:
    port: 4321

verification:
  environment: "dev"
