namespace: ubirch-demo
image:
  tag: latest # set to your local image tag if needed

# settings for ingest
keyServiceURL: "key-service-core-demo.core-demo.svc.cluster.local:8095"
kafkaURL: "kafka.core-demo.svc.cluster.local:9092"
redisSecretName: "redis-secrets-avatar"
serverUuid: "10b2e1a4-56b3-4fff-9ada-cc8c20f93016"

redis:
  masterURL: "redis-stable-master.core-demo.svc.cluster.local:6379"
  slaveURL: "redis-stable-slave.core-demo.svc.cluster.local:6379"

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-demo"
    certmanager.k8s.io/acme-dns01-provider: "demo-dns-demo-ubirch-com"
    kubernetes.io/ingress.allow-http: "false"
  path: /
  hosts:
    - demo.ubirch.com
  tls: #could I remove this?
    - secretName: niomon-demo-ubirch-com-certificate
      hosts:
        - niomon.demo.ubirch.com
